accounts/urls.py
from django.urls import path
from accounts.views import ProfileView, LoginView, LogoutView, RegistrationView, CustomChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('registration-done/', LogoutView.as_view(), name='registration-done'),
    path('change-password/', CustomChangePasswordView.as_view(), name='change-password'),
]

cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from orders.views import order_create_view

app_name = 'orders'

urlpatterns = [
    path('create-order/', order_create_view, name='create-order'),
]

shop/urls.py
from django.urls import path
from shop.views import (
    HomeView,
    NotebookPcView,
    PobutovaTechnikaView,
    TovariDlyaDomuView,
    SportZahoplennyaView,
    SmartphoneElektronicaView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('noutbuki-ta-kompyuteri/', NotebookPcView.as_view(), name='noutbuki-ta-kompyuteri'),
    path('pobutova-tehnika/', PobutovaTechnikaView.as_view(), name='pobutova-tehnika'),
    path('tovari-dlya-domu/', TovariDlyaDomuView.as_view(), name='tovari-dlya-domu'),
    path('sport-i-zahoplennya/', SportZahoplennyaView.as_view(), name='sport-i-zahoplennya'),
    path('smartfoni-tv-i-elektornika/', SmartphoneElektronicaView.as_view(), name='smartfoni-tv-i-elektornika'),
    path('product_detail/<slug:catalog_slug>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, label ='',
        widget=forms.Select(attrs={'class': 'form-select form-select-sm'})
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        return redirect('cart:cart_detail')

@require_POST
def cart_refresh_quantity(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% block title %} Кошик покупок {% endblock %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col my-4">
                <div class="card p-3">
                    <h3 style="card-title">Кошик покупок</h3>
                    <div class="card-body">
                        {% if cart %}
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <div class="card mb-3">
                                        <div class="row g-0 d-flex justify-content-center align-items-center">
                                            <div class="col-md-2">
                                                <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                                    <div class="wrap-img d-flex">
                                                        <img src="{{ product.image.url }}" style="max-height: 125px; max-width: 100%;" class="mx-auto" alt="{{ product.product_name }}">
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="card-body">
                                                    <h6 class="card-title">{{ product.product_name }}</h6>
                                                    <p>{{ product.description|truncatewords:15 }}</p>
                                                    <p>Кількість: {{ item.quantity }} </p>
                                                    <div class="justify-content-between d-flex">
                                                        <p class="align-items-center card-text" style="font-size: 20px;"><b>{{ product.price }} грн</b></p>
                                                        <form action="{% url 'cart:cart_remove' product.id %} " method="post">
                                                            {% csrf_token %}
                                                            <button type="submit" class="btn btn-sm btn-danger">Видалити</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endwith %}
                            {% endfor %}
                                {% if user.is_authenticated %}
                                    <h4 class="card-title text-center">Всього до сплати {{ cart.get_total_price }} грн.</h4>
                                    <div class="wrap-add-order text-center my-3">
                                        <button type="button" class="btn btn-success" >
                                            <a class="text-decoration-none" style="color: white;" href="{% url 'orders:create-order' %}">Зробити замовлення</a>
                                        </button>
                                    </div>
                                {% else %}
                                    <h4 class="card-title text-center">Всього до сплати {{ cart.get_total_price }} грн.</h4>
                                    <div class="wrap-add-order text-center my-3">
                                        <p>Щоб мати можливість оформити замовлення, Вам потрібно <a style="color: black" href="{% url 'accounts:login' %}">увійти</a> в профіль!</p>
                                    </div>
                                {% endif %}
                        {% else %}
                            <h4 class="text-center">Ваш список товарів порожній.</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}