accounts/urls.py
from django.urls import path
from accounts.views import ProfileView, LoginView, LogoutView, RegistrationView, CustomChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('registration-done/', LogoutView.as_view(), name='registration-done'),
    path('change-password/', CustomChangePasswordView.as_view(), name='change-password'),
]

cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models

# Create your models here.

class MyUserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Користувачі повинні мати email адресу!')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):

    f_name = models.CharField(
        verbose_name="Ім'я",
        max_length=50,
    )

    l_name = models.CharField(
        verbose_name='Прізвище',
        max_length=50,
    )

    phone_number = models.CharField(
        max_length=12,
        verbose_name="Номер телефону",
        null=True,
        blank=True,
        unique=True)

    email = models.EmailField(
        verbose_name='Email-адреса',
        max_length=50,
        unique=True,
    )

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    class Meta:
        verbose_name = 'Користувача'
        verbose_name_plural = 'Користувачі'



    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password

User = get_user_model()

class UserLoginForm(forms.Form):
    email = forms.CharField(
        label='Введіть email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Введіть пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password').strip()

        if email and password:
            qs = User.objects.filter(email=email)
            if not qs.exists():
                raise forms.ValidationError('Такого користувача не існує в системі!')
            if not check_password(password, qs[0].password):
                raise forms.ValidationError('Пароль не вірний!')

            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Даний користувач не активний у системі!')

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    f_name = forms.CharField(
        label="Ім'я",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    l_name = forms.CharField(
        label='Прізвище',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    phone_number = forms.CharField(
        label="Номер телефону",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    email = forms.EmailField(
        label='Email-адреса',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True,
    )
    password = forms.CharField(
        label='Введіть пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,
    )
    password2 = forms.CharField(
        label='Введіть пароль ще раз',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,
    )

    class Meta:
        model = User
        fields = ('f_name', 'l_name', 'phone_number', 'email',)

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Паролі не співпадають!')

        return data['password2']


class CustomChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Введіть старий пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,
    )
    new_password1 = forms.CharField(
        label='Введіть новий пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,
    )
    new_password2 = forms.CharField(
        label='Введіть новий пароль ще раз',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=True,
    )

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2',)

accounts/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, FormView, View
from accounts.forms import UserLoginForm, UserRegistrationForm, CustomChangePasswordForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse_lazy
from orders.models import Order
from django.contrib.auth.views import PasswordChangeView

# Create your views here.

User = get_user_model()

class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['orders_list'] = Order.objects.filter(user=self.request.user)
        return context


class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = UserLoginForm

    def form_valid(self, form):
        data = form.cleaned_data
        email = data.get('email')
        password = data.get('password')
        user = authenticate(self.request, email=email, password=password)
        login(self.request, user)
        return redirect('accounts:profile')


class LogoutView(View):

    def get(self, *args):
        logout(self.request)
        return redirect('accounts:login')


class RegistrationView(FormView):
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm

    def form_valid(self, form):
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        return render(self.request, 'accounts/registration_done.html', {'form': form})


class CustomChangePasswordView(PasswordChangeView):
    template_name = 'accounts/change_password.html'
    form_class = CustomChangePasswordForm
    success_url = reverse_lazy('accounts:profile')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Зміна паролю {% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <h3 class="card-title text-center">Зміна паролю</h3>
                    <div class="card-body">
                        <form method="POST" action="">{% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="wrap-btn text-center">
                                <button type="submit" class="btn btn-primary">Зберегти</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Вхід в профіль користувача {% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <h3 class="card-title text-center">Вхід в профіль користувача</h3>
                    <div class="card-body">
                        <form method="POST" action="">{% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="wrap-btn d-flex align-items-center justify-content-between">
                                <button type="submit" class="btn btn-primary">Увійти</button>
                                <a class="text-decoration-none" style="color: #212529;" href="#reset-password">Забули пароль?</a>
                            </div>
                            <div class="wrap-registration text-center my-3">
                                <button type="button" class="btn btn-secondary" >
                                    <a class="text-decoration-none" style="color: white;" href="{% url 'accounts:registration' %}">Зареєструватися</a>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Профіль користувача {% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-3">
            <div class="col">
                <div class="card p-3">
                    <h3 class="card-title text-center">Профіль користувача</h3>
                    <div class="card-body">
                        {% if user.is_authenticated %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="contact-inform">
                                        <h4>Контактна інформація:</h4>
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="contact-inform-wrap d-flex align-items-center justify-content-start">
                                                    <img style="max-height: 125px; max-width: 100%;" src="{% static 'img/user-profile.png' %}" alt="">
                                                    <div class="contact-inform-descr ms-2">
                                                        <span><b>Ім'я:</b> {{ user.f_name }}</span> <br>
                                                        <span><b>Прізвище:</b> {{ user.l_name }}</span> <br>
                                                        <span><b>Телефон:</b> +{{ user.phone_number }}</span> <br>
                                                        <span><b>Email-адрес:</b> {{ user.email }}</span>
                                                    </div>
                                                </div>
                                                <div class="btn-wrapper text-center my-3">
                                                    <button type="button" class="btn btn-sm btn-primary" >
                                                        <a class="text-decoration-none" style="color: white;" href="{% url 'accounts:change-password' %}">Зміна пароля</a>
                                                    </button>
                                                    <button type="button" class="btn btn-sm btn-danger ms-2" >
                                                        <a class="text-decoration-none" style="color: white;" href="{% url 'accounts:logout' %}">Вихід з профілю</a>
                                                    </button>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="orders-inform">
                                        <h4 class="card-title">Мої замовлення:</h4>
                                        {% if orders_list %}
                                            {% for order in orders_list %}
                                                <div class="card mb-3">
                                                    <div class="orders-inform-title text-center">
                                                        <b>{{ order }}</b>
                                                    </div>
                                                    <div class="card-body">
                                                        {% for item in order.items.all %}
                                                            <div class="wrap-img d-flex mb-2">
                                                                <img src="{{ item.product.image.url }}" style="max-height: 125px; max-width: 100%;" class="mx-auto" alt="{{ product.product_name }}">
                                                            </div>
                                                            <b>{{ item.product }}</b>
                                                            <p><b>{{ item.product.price }} грн.</b></p>
                                                        {% endfor %}
                                                        <span><b>Cтатус:</b> {{ order.status }}</span><br>
                                                        <span><b>Було створено:</b> {{ order.created }}</span><br>
                                                        <span><b>Було оновлено:</b> {{ order.updated }}</span><br>
                                                        <span><b>До сплати:</b> {{ order.get_total_cost }} грн.</span>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% else %}
                                            <div class="card p-2">
                                                <p>Ви ще не замовляли товари!</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                        {% else %}
                            <p>data is empty</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Реєстрація користувача {% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <h3 class="card-title text-center">Реєстрація користувача</h3>
                    <div class="card-body">
                        <form method="POST" action="">{% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="wrap-btn text-center">
                                <button type="submit" class="btn btn-primary">Зареєструватися</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/registration_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Реєстрація прошла успішно! {% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <h3 class="card-title text-center">Реєстрація пройшла успішно!</h3>
                    <div class="card-body">
                        <div class="wrap-registration text-center my-3">
                            <a class="text-decoration-none" style="color: #212529;" href="{% url 'accounts:login' %}">Увійти в профіль користувача</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}