accounts/urls.py
from django.urls import path
from accounts.views import ProfileView, LoginView, LogoutView, RegistrationView, CustomChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('registration-done/', LogoutView.as_view(), name='registration-done'),
    path('change-password/', CustomChangePasswordView.as_view(), name='change-password'),
]

cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from shop.views import (
    HomeView,
    NotebookPcView,
    PobutovaTechnikaView,
    TovariDlyaDomuView,
    SportZahoplennyaView,
    SmartphoneElektronicaView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('noutbuki-ta-kompyuteri/', NotebookPcView.as_view(), name='noutbuki-ta-kompyuteri'),
    path('pobutova-tehnika/', PobutovaTechnikaView.as_view(), name='pobutova-tehnika'),
    path('tovari-dlya-domu/', TovariDlyaDomuView.as_view(), name='tovari-dlya-domu'),
    path('sport-i-zahoplennya/', SportZahoplennyaView.as_view(), name='sport-i-zahoplennya'),
    path('smartfoni-tv-i-elektornika/', SmartphoneElektronicaView.as_view(), name='smartfoni-tv-i-elektornika'),
    path('product_detail/<slug:catalog_slug>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{% static 'img/logo.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %} Rozetka-e-commerce {% endblock %}</title>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand brand-font" href="{% url 'shop:home' %}">
          <img class="rozetka-logo" src="{% static 'img/logo.ico' %}" alt="logo">
          Rozetka-e-commerce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle me-3" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Каталог товарів
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'shop:pobutova-tehnika' %}">Побутова техніка</a></li>
              <li><a class="dropdown-item" href="{% url 'shop:noutbuki-ta-kompyuteri' %}">Ноутбуки та комп'ютери</a></li>
              <li><a class="dropdown-item" href="{% url 'shop:tovari-dlya-domu' %}">Товари для дому</a></li>
              <li><a class="dropdown-item" href="{% url 'shop:sport-i-zahoplennya' %}">Спорт і захоплення</a></li>
              <li><a class="dropdown-item" href="{% url 'shop:smartfoni-tv-i-elektornika' %}">Смартфони, ТВ і електроніка</a></li>
            </ul>
          </li>
          </ul>
          <form method="get" action="/search" class="d-flex w-100">
            <input class="form-control me-2" type="search" placeholder="Пошук товарів" aria-label="Search" name="query" id="querys">
            <button class="btn btn-success" type="submit">Пошук</button>
          </form>
          <li class="nav-item d-flex">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'accounts:profile' %}" tabindex="-1" aria-disabled="true"><img class="cart-logo" src="{% static 'img/user.svg' %}" alt="account"></a>
            {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}" tabindex="-1" aria-disabled="true"><img class="cart-logo" src="{% static 'img/user.svg' %}" alt="account"></a>
            {% endif %}
          </li>
          <li class="nav-item d-flex align-items-center justify-content-center">
            {% if cart %}
                <a class="nav-link" href="{% url 'cart:cart_detail' %}" tabindex="-1" aria-disabled="true"><img class="cart-logo" src="{% static 'img/shopping-cart.svg' %}" alt="cart"></a>
                <span style="color: #8a939a;">+{{ cart.get_total_product }}</span>
            {% else %}
                <a class="nav-link" href="{% url 'cart:cart_detail' %}" tabindex="-1" aria-disabled="true"><img class="cart-logo" src="{% static 'img/shopping-cart.svg' %}" alt="cart"></a>
                <span style="color: #8a939a;">+{{ cart.get_total_product }}</span>
            {% endif %}
          </li>

        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>


    <!-- Footer -->
    <footer class="page-footer font-small blue pt-4 mt-auto" style=" color: white;"> <!-- background-color: #394047; -->
      <!-- Footer Links -->
<!--      <div class="container text-center text-md-left">-->

<!--        &lt;!&ndash; Grid row &ndash;&gt;-->
<!--        <div class="row">-->

<!--          &lt;!&ndash; Grid column &ndash;&gt;-->
<!--          <div class="col-md-6 mt-md-0 mt-3">-->

<!--            &lt;!&ndash; Content &ndash;&gt;-->
<!--            <h5 class="text-uppercase">Footer Content</h5>-->
<!--            <p>Here you can use rows and columns to organize your footer content.</p>-->

<!--          </div>-->
<!--          &lt;!&ndash; Grid column &ndash;&gt;-->

<!--          <hr class="clearfix w-100 d-md-none pb-3">-->

<!--          &lt;!&ndash; Grid column &ndash;&gt;-->
<!--          <div class="col-md-3 mb-md-0 mb-3">-->

<!--            &lt;!&ndash; Links &ndash;&gt;-->
<!--            <h5 class="text-uppercase">Links</h5>-->

<!--            <ul class="list-unstyled">-->
<!--              <li>-->
<!--                <a href="#!">Link 1</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 2</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 3</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 4</a>-->
<!--              </li>-->
<!--            </ul>-->

<!--          </div>-->
<!--          &lt;!&ndash; Grid column &ndash;&gt;-->

<!--          &lt;!&ndash; Grid column &ndash;&gt;-->
<!--          <div class="col-md-3 mb-md-0 mb-3">-->

<!--            &lt;!&ndash; Links &ndash;&gt;-->
<!--            <h5 class="text-uppercase">Links</h5>-->

<!--            <ul class="list-unstyled">-->
<!--              <li>-->
<!--                <a href="#!">Link 1</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 2</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 3</a>-->
<!--              </li>-->
<!--              <li>-->
<!--                <a href="#!">Link 4</a>-->
<!--              </li>-->
<!--            </ul>-->

<!--          </div>-->
<!--          &lt;!&ndash; Grid column &ndash;&gt;-->

<!--        </div>-->
<!--        &lt;!&ndash; Grid row &ndash;&gt;-->

<!--      </div>-->
<!--      &lt;!&ndash; Footer Links &ndash;&gt;-->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3" style="background-color: #212529;">Сайт було розроблено в якості pet-проекту:
        <a style="color: white;" href="https://t.me/DoZoR_MO">контакти розробника</a>
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>