cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from shop.views import (
    HomeView,
    NotebookPcView,
    PobutovaTechnikaView,
    TovariDlyaDomuView,
    SportZahoplennyaView,
    SmartphoneElektronicaView,
    ProductDetailView,
    SearchView
)

app_name = 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('noutbuki-ta-kompyuteri/', NotebookPcView.as_view(), name='noutbuki-ta-kompyuteri'),
    path('pobutova-tehnika/', PobutovaTechnikaView.as_view(), name='pobutova-tehnika'),
    path('tovari-dlya-domu/', TovariDlyaDomuView.as_view(), name='tovari-dlya-domu'),
    path('sport-i-zahoplennya/', SportZahoplennyaView.as_view(), name='sport-i-zahoplennya'),
    path('smartfoni-tv-i-elektornika/', SmartphoneElektronicaView.as_view(), name='smartfoni-tv-i-elektornika'),
    path('product_detail/<slug:catalog_slug>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
]

shop/models.py
from django.db import models

# Create your models here.

class Catalog(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва")
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    class Meta:
        verbose_name = 'Каталог товару'
        verbose_name_plural = 'Каталоги товарів'

    def __str__(self):
        return self.name


class Characteristic(models.Model):
    admin_panel_name = models.CharField(max_length=255, verbose_name='Назва в панеі адміністратора', default='')
    filter_name = models.CharField(max_length=255, verbose_name='Назва для фільтру', default='', blank=True)
    characteristic = models.CharField(max_length=255, verbose_name='Назва')
    value = models.CharField(max_length=255, verbose_name='Значення')

    class Meta:
        verbose_name='Характеристика товару'
        verbose_name_plural = 'Характеристики товарів'

    def __str__(self):
        return self.admin_panel_name


class Product(models.Model):
    CHOICE_STATUS = (
        ('draft', 'В обробці'),
        ('published', 'Опубліковано')
    )

    catalog = models.ForeignKey(Catalog, on_delete=models.CASCADE, verbose_name='Каталог товарів')
    product_name = models.CharField(max_length=100, verbose_name="Назва товару")
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    image = models.ImageField(upload_to='img/products/', blank=True)
    description = models.TextField(verbose_name='Опис товару', blank=True)
    characteristics = models.ManyToManyField(Characteristic, verbose_name='Характеристики')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    publish = models.DateField(editable=True, auto_now_add=True, verbose_name='Опубліковано')
    updated = models.DateField(editable=True, auto_now=True, verbose_name='Оновлено')
    status = models.CharField(max_length=10, choices=CHOICE_STATUS, default='draft', verbose_name='Статус')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'
        ordering = ('-publish',)

    def __str__(self):
        return self.product_name

shop/views.py
from shop.models import Product, Characteristic
from django.views.generic import ListView, DetailView, FormView
from django.db.models import Q
from cart.forms import CartAddProductForm

# Create your views here.

class HomeView(ListView, FormView):

    template_name = 'shop/home.html'
    context_object_name = 'product_list'
    paginate_by = 8
    form_class = CartAddProductForm

    def get_queryset(self):
        queryset = Product.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = self.form_class
        return context

class CharactericsticsView():

    ##### NotebookPcView filter #####

    def get_manufacturer(self):
        return Characteristic.objects.filter(filter_name='get_manufacturer_pcnout')

    def get_cpu(self):
        return Characteristic.objects.filter(filter_name='get_cpu_pcnout')

    def get_gpu(self):
        return Characteristic.objects.filter(filter_name='get_gpu_pcnout')

    def get_ram(self):
        return Characteristic.objects.filter(filter_name='get_ram_pcnout')

    def get_hdd(self):
        return Characteristic.objects.filter(filter_name='get_hdd_pcnout')

    def get_weight(self):
        return Characteristic.objects.filter(filter_name='get_weight_pcnout')

    def get_sizes(self):
        return Characteristic.objects.filter(filter_name='sizes')

    def get_powersupply(self):
        return Characteristic.objects.filter(filter_name='get_powersupply_pcnout')


    ##### PobutovaTechnikaView filter #####

    def get_pob_manufacturer(self):
        return Characteristic.objects.filter(filter_name='get_pob_manufacturer')


    ##### TovariDlyaDomuView filter #####

    def get_tov_manufacturer(self):
        return Characteristic.objects.filter(filter_name='get_tov_manufacturer')


    ##### SportZahoplennyaView filter #####

    def get_sport_manufacturer(self):
        return Characteristic.objects.filter(filter_name='get_sport_manufacturer')


    ##### SmartphoneElektronicaView filter #####

    def get_smartelectron_manufacturer(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_manufacturer')

    def get_smartelectron_cpu(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_cpu')

    def get_smartelectron_weight(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_weight')

    def get_smartelectron_screen_size(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_screen_size')

    def get_smartelectron_matrix_type(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_matrix_type')

    def get_smartelectron_harddrive(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_harddrive')

    def get_smartelectron_ram_size(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_ram_size')

    def get_smartelectron_os(self):
        return Characteristic.objects.filter(filter_name='get_smartelectron_os')



class NotebookPcView(CharactericsticsView, ListView, FormView):

    template_name = 'shop/noutbuki-ta-kompyuteri.html'
    context_object_name = 'product_list'
    form_class = CartAddProductForm

    def get_queryset(self):

        queryset = Product.objects.filter(catalog__slug='noutbuki-ta-kompyuteri')

        if self.request.GET:

            if self.request.GET.getlist('min_price'):

                min_price = self.request.GET.getlist('min_price')
                max_price = self.request.GET.getlist('max_price')

                queryset = Product.objects.filter(
                    Q(catalog__slug='noutbuki-ta-kompyuteri'),
                    Q(price__range = (min_price[0], max_price[0]))
                ).distinct()

                return queryset

            queryset = Product.objects.filter(
                Q(catalog__slug='noutbuki-ta-kompyuteri'),
                Q(characteristics__value__in = self.request.GET.getlist('manufacturer')) |
                Q(characteristics__value__in = self.request.GET.getlist('cpu')) |
                Q(characteristics__value__in = self.request.GET.getlist('gpu')) |
                Q(characteristics__value__in = self.request.GET.getlist('ram')) |
                Q(characteristics__value__in = self.request.GET.getlist('harddisk')) |
                Q(characteristics__value__in = self.request.GET.getlist('weight')) |
                Q(characteristics__value__in = self.request.GET.getlist('powersupply'))
            ).distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = self.form_class
        return context


class PobutovaTechnikaView(CharactericsticsView, ListView, FormView):

    template_name = 'shop/pobutova-tehnika.html'
    context_object_name = 'product_list'
    form_class = CartAddProductForm

    def get_queryset(self):

        queryset = Product.objects.filter(catalog__slug='pobutova-tehnika')

        if self.request.GET:

            if self.request.GET.getlist('min_price'):

                min_price = self.request.GET.getlist('min_price')
                max_price = self.request.GET.getlist('max_price')

                queryset = Product.objects.filter(
                    Q(catalog__slug='pobutova-tehnika'),
                    Q(price__range = (min_price[0], max_price[0]))
                ).distinct()

                return queryset

            queryset = Product.objects.filter(
                Q(catalog__slug='pobutova-tehnika'),
                Q(characteristics__value__in = self.request.GET.getlist('manufacturer'))
            ).distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = self.form_class
        return context


class TovariDlyaDomuView(CharactericsticsView, ListView, FormView):

    template_name = 'shop/tovari-dlya-domu.html'
    context_object_name = 'product_list'
    form_class = CartAddProductForm

    def get_queryset(self):

        queryset = Product.objects.filter(catalog__slug='tovari-dlya-domu')

        if self.request.GET:

            if self.request.GET.getlist('min_price'):

                min_price = self.request.GET.getlist('min_price')
                max_price = self.request.GET.getlist('max_price')

                queryset = Product.objects.filter(
                    Q(catalog__slug='tovari-dlya-domu'),
                    Q(price__range = (min_price[0], max_price[0]))
                ).distinct()

                return queryset

            queryset = Product.objects.filter(
                Q(catalog__slug='tovari-dlya-domu'),
                Q(characteristics__value__in = self.request.GET.getlist('manufacturer'))
            ).distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = self.form_class
        return context


class SportZahoplennyaView(CharactericsticsView, ListView, FormView):

    template_name = 'shop/sport-i-zahoplennya.html'
    context_object_name = 'product_list'
    form_class = CartAddProductForm

    def get_queryset(self):

        queryset = Product.objects.filter(catalog__slug='sport-i-zahoplennya')

        if self.request.GET:

            if self.request.GET.getlist('min_price'):
                min_price = self.request.GET.getlist('min_price')
                max_price = self.request.GET.getlist('max_price')

                queryset = Product.objects.filter(
                    Q(catalog__slug='sport-i-zahoplennya'),
                    Q(price__range=(min_price[0], max_price[0]))
                ).distinct()

                return queryset

            queryset = Product.objects.filter(
                Q(catalog__slug='sport-i-zahoplennya'),
                Q(characteristics__value__in=self.request.GET.getlist('manufacturer'))
            ).distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = self.form_class
        return context


class SmartphoneElektronicaView(CharactericsticsView, ListView, FormView):

    template_name = 'shop/smartfoni-tv-i-elektornika.html'
    context_object_name = 'product_list'
    form_class = CartAddProductForm

    def get_queryset(self):

        queryset = Product.objects.filter(catalog__slug='smartfoni-tv-i-elektornika')

        if self.request.GET:

            if self.request.GET.getlist('min_price'):

                min_price = self.request.GET.getlist('min_price')
                max_price = self.request.GET.getlist('max_price')

                queryset = Product.objects.filter(
                    Q(catalog__slug='smartfoni-tv-i-elektornika'),
                    Q(price__range = (min_price[0], max_price[0]))
                ).distinct()

                return queryset

            queryset = Product.objects.filter(
                Q(catalog__slug='smartfoni-tv-i-elektornika'),
                Q(characteristics__value__in = self.request.GET.getlist('manufacturer')) |
                Q(characteristics__value__in=self.request.GET.getlist('cpu')) |
                Q(characteristics__value__in=self.request.GET.getlist('os')) |
                Q(characteristics__value__in=self.request.GET.getlist('screen_size')) |
                Q(characteristics__value__in=self.request.GET.getlist('weight')) |
                Q(characteristics__value__in=self.request.GET.getlist('matrix_type')) |
                Q(characteristics__value__in=self.request.GET.getlist('ram_size')) |
                Q(characteristics__value__in=self.request.GET.getlist('harddrive'))
            ).distinct()

        return queryset

    def get_context_data(self, **kwargs):

shop/templates/shop/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Головна | Rozetka-e-commerce {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            <nav class="nav flex-column my-3">
                <h5>Популярні запити</h5>
                <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:pobutova-tehnika' %}">Побутова техніка</a>
                <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:noutbuki-ta-kompyuteri' %}">Ноутбуки та комп'ютери</a>
                <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:tovari-dlya-domu' %}">Товари для дому</a>
                <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:sport-i-zahoplennya' %}">Спорт і захоплення</a>
                <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:smartfoni-tv-i-elektornika' %}">Смартфони, ТВ і електроніка</a>
            </nav>
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="col m-3">
                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="{% static 'img/slide-1.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-2.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-3.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-4.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-5.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-6.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-7.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-8.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-9.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/slide-10.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                        </a>
                    </div>
                </div>
            </div>

            <h2 class="text-center my-4 ">Останні додані товари</h2>

            {% if product_list %}
                <div class="row g-4 m-2">
                    {% for product in product_list %}
                    <div class="col-md-3">
                        <div class="card">
                            <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                <div class="wrap-img d-flex">
                                    <img src="{{ product.image.url }}" style="max-height: 125px; max-width: 100%;" class="mx-auto" alt="{{ product.product_name }}">
                                </div>
                            </a>
                            <div class="card-body">
                                <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                    <h6 class="card-title">{{ product.product_name }}</h6>
                                </a>
                                <div class="justify-content-between align-items-center d-flex">
                                    <p class="card-text" style="font-size: 20px;"><b>{{ product.price }} грн</b></p>
                                    <div class="btn-cart-wrapper">
                                        <form class="d-flex" action="{% url 'cart:cart_add' product.id %}" method="post">
                                            {% csrf_token %}
                                            {{ cart_form }}
                                            <button class="btn btn-sm" type="submit" tabindex="-1" aria-disabled="true">
                                                <img class="cart-logo" style="height: 25px;" src="{% static 'img/cart-green.svg' %}" alt="cart">
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                {% if is_paginated %}
                    <div class="row">
                        <div class="col">
                            <div class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
                                    </li>
                                {% endif %}

                                {% for page in page_obj.paginator.page_range %}
                                    {% if page_obj.number == page %}
                                        <li class="page-item active">
                                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% elif page > page_obj.number|add:-5 and page < page_obj.number|add:5 %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Наступна</a>
                                    </li>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <p>Очікуємо товар...</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

shop/templates/shop/pobutova-tehnika.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Побутова техніка {% endblock %}

{% block content %}
    <div class="row my-3">
        <div class="col-md-2">
           <form action="{% url 'shop:pobutova-tehnika' %}" method="get">
              <div class="wrap-form-title d-flex justify-content-between align-items-center mb-2">
                 <h5>Фільтри</h5>
                 <input class="btn-sm btn-dark" type="submit" value="Пошук за фільтром">
              </div>
              <div class="card">
                 <article class="card-group-item">
                    <header class="card-header">
                       <h6 class="title">Виробник</h6>
                    </header>
                    <div class="filter-content">
                       <div class="card-body">
                          {% for manufacturer in view.get_pob_manufacturer %}
                          <div class="form-check">
                             <input class="form-check-input checked-style" type="checkbox" name="manufacturer" value="{{ manufacturer.value }}">
                             <label class="form-check-label">
                             {{ manufacturer.value }}
                             </label>
                          </div>
                          <!-- form-check.// -->
                          {% endfor %}
                       </div>
                       <!-- card-body.// -->
                    </div>
                 </article>
                 <!-- card-group-item.// -->
              </div>
              <!-- card.// -->
           </form>

           <form action="{% url 'shop:pobutova-tehnika' %}" method="get">
              <div class="card">
                 <article class="card-group-item">
                    <header class="card-header">
                       <h6 class="title">Ціна</h6>
                    </header>
                    <div class="filter-content">
                       <div class="card-body">
                          <div class="form-row">
                             <div class="form-group">
                                <div class="value-wrap d-flex justify-content-between">
                                   <div class="min">0 <span>грн</span></div>
                                   <div class="max">100000 <span>грн</span></div>
                                </div>
                                <div class="multi-range-slider">
                                   <input type="range" id="input-left" name="min_price" min="0" max="100000" value="0">
                                   <input type="range" id="input-right" name="max_price" min="0"  max="100000" value="100000">
                                   <div class="slider">
                                      <div class="track"></div>
                                      <div class="range"></div>
                                   </div>
                                </div>
                                <button class="btn-sm btn-dark d-flex mx-auto" type="submit">Ok</button>
                             </div>
                          </div>
                       </div>
                       <!-- card-body.// -->
                    </div>
                 </article>
                 <!-- card-group-item.// -->
              </div>
              <!-- card.// -->
           </form>
        </div>

        <div class="col-md-10 my-3">
            <h3>Побутова техніка</h3>
            <div class="row g-4 m-2">
                {% if product_list %}
                    {% for product in product_list %}
                        <div class="col-md-3">
                            <div class="card">
                                <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                    <div class="wrap-img d-flex">
                                        <img src="{{ product.image.url }}" style="max-height: 125px; max-width: 100%;" class="mx-auto" alt="{{ product.product_name }}">
                                    </div>
                                </a>
                                <div class="card-body">
                                    <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                        <h6 class="card-title">{{ product.product_name }}</h6>
                                    </a>
                                    <p>{{ product.description|truncatewords:11 }}</p>
                                    <div class="justify-content-between align-items-center d-flex">
                                        <p class="card-text" style="font-size: 20px;"><b>{{ product.price }} грн</b></p>
                                        <div class="btn-cart-wrapper">
                                            <form class="d-flex" action="{% url 'cart:cart_add' product.id %}" method="post">
                                                {% csrf_token %}
                                                {{ cart_form }}
                                                <button class="btn btn-sm" type="submit" tabindex="-1" aria-disabled="true">
                                                    <img class="cart-logo" style="height: 25px;" src="{% static 'img/cart-green.svg' %}" alt="cart">
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h4 class="text-center">Ваш запит не знайдено.</h4>
                {% endif %}
           </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Результати пошуку {% endblock %}

{% block content %}
<div class="row my-3">
    <div class="col-md-2">
        <nav class="nav flex-column">
            <h5>Популярні запити</h5>
            <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:pobutova-tehnika' %}">Побутова техніка</a>
            <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:noutbuki-ta-kompyuteri' %}">Ноутбуки та комп'ютери</a>
            <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:tovari-dlya-domu' %}">Товари для дому</a>
            <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:sport-i-zahoplennya' %}">Спорт і захоплення</a>
            <a class="nav-link text-decoration-none" style="color: black;" href="{% url 'shop:smartfoni-tv-i-elektornika' %}">Смартфони, ТВ і електроніка</a>
        </nav>
    </div>

    <div class="col-md-10">
        <h3>Результати пошуку</h3>
        <div class="row g-4 m-2">
            {% if product_list %}
                {% for product in product_list %}
                    <div class="col-md-3">
                        <div class="card">
                            <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                <div class="wrap-img d-flex">
                                    <img src="{{ product.image.url }}" style="max-height: 125px; max-width: 100%;" class="mx-auto" alt="{{ product.product_name }}">
                                </div>
                            </a>
                            <div class="card-body">
                                <a href="{% url 'shop:product_detail' product.catalog.slug product.slug %}" style="text-decoration: none; color: black;" class="card-link">
                                    <h6 class="card-title">{{ product.product_name }}</h6>
                                </a>
                                <p>{{ product.description|truncatewords:11 }}</p>
                                <div class="justify-content-between d-flex">
                                    <p class="align-items-center card-text" style="font-size: 20px;"><b>{{ product.price }} грн</b></p>
                                    <div class="btn-cart-wrapper">
                                        <form class="d-flex" action="{% url 'cart:cart_add' product.id %}" method="post">
                                            {% csrf_token %}
                                            {{ cart_form }}
                                            <button class="btn btn-sm" type="submit" tabindex="-1" aria-disabled="true">
                                                <img class="cart-logo" style="height: 25px;" src="{% static 'img/cart-green.svg' %}" alt="cart">
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h4 class="text-center">Ваш запит не знайдено.</h4>
            {% endif %}
       </div>
    </div>
</div>
{% endblock %}